# Computación Científica II
## Laboratorio  #4
    
   Gabriela González Toledo      gabriela.gonzalez@alumnos.usm.cl  201173017-8
   
   Ian Zamorano Escobedo         Ian.zamorano.12@sansano.usm.cl    201273018-k

In [2]:
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
import matplotlib.pyplot as plt

import timeit
from math import ceil, floor
from sympy import *
from sympy.abc import *
from scipy.special import gamma

#%load_ext line_profiler

### Introducción:

El presente laboratorio tiene como objetivo comprender y aplicar los métodos de Integración Numérica. Para esto implementaremos  los cuatro métodos vistos en clases. En la primera parte trabajaremos aplicando los métodos a una integral impropia, haciendo un cambio de variable y calculando los tiempos de ejecución de cada método. La segunda parte consta de implementar un método para calcular derivadas fraccionarias y hacer cálculos de algunas derivadas para luego analizar su comportamiento al variar la fracción entre sus enteros superior e inferior.

### Diferencias Finitas en 2D

#### 1. Esquema de discretización forward:

$$
\partial_t u = D_u \Delta u + \lambda u - u^3 - \kappa - \sigma􀀀 v
$$
$$
\tau \partial_t v = D_v \Delta v + u -􀀀 v
$$

$$
u \rightarrow w
$$

$$
v \rightarrow q
$$

$$
w_{i,j,k} = u(x_i,y_j,t_k) = u(i\Delta x, j\Delta y, k \Delta t) \qquad i,j,k \in \{1,2,3, \dots , N\}
$$
$$
q_{i,j,k} = v(x_i,y_j,t_k) = v(i\Delta x, j\Delta y, k \Delta t) \qquad i,j,k \in \{1,2,3, \dots , N\}
$$

$$
w_{xx} = \cfrac{w_{i-1,j,k} - 2 w_{i,j,k} + w_{i+1,j,k}}{\Delta x^{2}}
$$

$$
w_{yy} = \cfrac{w_{i,j-1,k} - 2 w_{i,j,k} + w_{i,j+1,k}}{\Delta y^{2}}
$$

$$
w_{t} = \cfrac{w_{i,j,k+1} - w_{i,j,k}}{\Delta t}
$$



$$
\cfrac{w_{i,j,k+1} - w_{i,j,k}}{\Delta t} = D_w \left( \cfrac{w_{i-1,j,k} - 2 w_{i,j,k} + w_{i+1,j,k}}{\Delta x^{2}} + \cfrac{w_{i-1,j,k} - 2 w_{i,j,k} + w_{i+1,j,k}}{\Delta x^{2}} \right) + \lambda w_{i,j,k} - w_{i,j,k}^3 - \kappa - \sigma􀀀 q_{i,j,k}
$$

$$
\tau \cfrac{q_{i,j,k+1} - q_{i,j,k}}{\Delta t} = D_q \left( \cfrac{q_{i-1,j,k} - 2 q_{i,j,k} + q_{i+1,j,k}}{\Delta x^{2}} + \cfrac{q_{i-1,j,k} - 2 q_{i,j,k} + q_{i+1,j,k}}{\Delta x^{2}} \right) +  w_{i,j,k} -􀀀  q_{i,j,k}
$$

$$
~
$$

$$
w_{i,j,k+1}  = \Delta t \left[ D_w \left( \cfrac{w_{i-1,j,k} - 2 w_{i,j,k} + w_{i+1,j,k}}{\Delta x^{2}} + \cfrac{w_{i-1,j,k} - 2 w_{i,j,k} + w_{i+1,j,k}}{\Delta x^{2}} \right) + \lambda w_{i,j,k} - w_{i,j,k}^3 - \kappa - \sigma􀀀 q_{i,j,k} \right] + w_{i,j,k}
$$

$$
q_{i,j,k+1}  = \cfrac{ \Delta t \left[ D_q \left( \cfrac{q_{i-1,j,k} - 2 q_{i,j,k} + q_{i+1,j,k}}{\Delta x^{2}} + \cfrac{q_{i-1,j,k} - 2 q_{i,j,k} + q_{i+1,j,k}}{\Delta x^{2}} \right) +  w_{i,j,k} -􀀀  q_{i,j,k} \right]}{\tau } + q_{i,j,k}
$$


#### 2. Desarrollo solve fordward:

In [18]:
p = np.array([[1,2,2,1], [2,5,4,2], [3,4,5,3], [2,2,2,2]])
T = np.array([[0,1,0,0], [0,-2,1,0], [0,1,-2,0], [0,0,1,0]])
idf = np.array([[0,0,0,0], [0,1,0,0], [0,0,1,0], [0,0,0,0]])
print T
print p
print idf
res = np.dot(p,T)
print np.dot(res,idf)


[[ 0  1  0  0]
 [ 0 -2  1  0]
 [ 0  1 -2  0]
 [ 0  0  1  0]]
[[1 2 2 1]
 [2 5 4 2]
 [3 4 5 3]
 [2 2 2 2]]
[[0 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 0]]
[[ 0 -1 -1  0]
 [ 0 -4 -1  0]
 [ 0  0 -3  0]
 [ 0  0  0  0]]


#### 3.  Discretizacion de ecuacion de onda

#### 4. Analisis de sensibilidad

#### 5. Resolucion del problema.

### Analisis práctico

#### 1. Cambio de variable

#### 2.Implementación  

#### 3. Cálculo de integrales

### Conclusión: